aiverify-foundation/moonshot-ui

app/views/attackmodules/attackModuleSelector.tsx, app/views/attackmodules/attackModulesViewList.tsx
=> fix attack module typos

app/views/benchmarking/benchmarkReportSectionOne.tsx, app/views/benchmarking/benchmarkRunsView.tsx, app/views/redteaming/redteamNewSessionFlow.tsx
Fix few more endpoint wordings
=> endpoint typos

.github/workflows/ci.yml
Allows for specification of Branch Name to pull the right branch for unit testing for Moonshot UI
Provides a Manual Way to trigger Unit Test for Moonshot-UI
Allows for ad-hoc trigger of Unit Test for Moonshot-UI
- ci: Changes to the CI/CD configuration or scripts
<details>
``` …
```
=> Manual Unit Test Trigger

.github/workflows/sca-scan.yaml
Add Blackduck Scanning On Pull Request & Work Dispatch
To enable Vulnerabilities & License Scans On Pull Request & Work Dispatch
- ci: Changes to the CI/CD configuration or scripts
Run Blackduck Scanning Workflow On Pull Request & Work Dispatch
<details>
```
Version 1.1
Developer's Certificate of Origin 1.1
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it …
```
=> Add Software Composition Analysis Scan

app/components/selectInput/index.tsx, app/endpoints/(edit)/_tests_/newEndpointForm.test.tsx, app/endpoints/(edit)/newEndpointForm.tsx, app/global.d.ts, app/lib/_tests_/error-utils.test.ts, app/lib/error-utils.ts
In edit endpoint user flow, save button is not enabled when form values other than token, is updated. Issue caused by code changes in previous PR for endpoint form.
Code changes include correcting select input component label 'for' attribute and improvement to error util function.
bug fix
1. Go to endpoints screen
2. Select an endpoint and click 'edit endpoint' button
Save button should be disabled by default and enabled when form values are changed. Also verify endpoint is updated when save button is clicked.
Regression required for new endpoint flow.
- [ x]  I have read, understood and agree to the Developer Certificate of Origin below, which this …
=> Fix edit endpoint form save button not enabled

app/benchmarking/cookbooks/page.tsx
hotfix - cookbooks page prerendered at build time causes an issue when started up using command `python -m moonshot web` - error report during build (TypeError - fetch)
issue in python moonshot web startup
- [ x]  I have performed a self-review of my own code.
- [x ]  I have read, understood and agree to the Developer Certificate of Origin below, which this project utilises.
[If the changes involve visual modifications, include screenshots or …
=> force cookbook list page to be dynamically rendered on demand

app/endpoints/(edit)/newEndpointForm.tsx, app/redteaming/(fullscreen)/components/bookmarksPanel.tsx, app/redteaming/(fullscreen)/components/viewBookmarksModal.tsx
Add a loading spinner on bookmarks panel while server action to fetch data is in progress
UX improvement
- [ x]  I have tested the changes locally and verified that they work as expected.
- [x ]  I have added or updated the necessary documentation (README, API docs, etc.).
- [x ]  I have read, understood and agree to the Developer Certificate of Origin below, which this project utilises.
[If the changes involve visual modifications, include screenshots or GIFs that …
=> Bookmarks panel - loading animation pending state

.github/workflows/smoke-test.yaml
Add Smoke Test Workflow
Smoke Test is used for quick verification of build to ensure that Core User Flow is stable.
- ci: Changes to the CI/CD configuration or scripts
Run Smoke Test Workflow on the GitHub Actions Pipeline.
<details>
```
Version 1.1
Developer's Certificate …
```
=> Add Smoke Test Workflow

.gitignore, app/api/v1/runners/route.ts, app/components/notifications.tsx, app/endpoints/(edit)/_tests_/newEndpointForm.test.tsx, package-lock.json, package.json
Fixes the issue where status panel of newly run test displays run id instead of run name
bug fix
1. Start a new benchmark test run
2. While it is running, open the status panel (bell icon) and verify the run name
<details>
```
Version 1.1
Developer's …
```
=> fix run name on status panel

app/benchmarking/components/cookbooksSelection.tsx, moonshot.config.ts
There are currently no cookbooks under `quality` categories in the tabbed cookbooks selection page., so removing the tab.
tidy up unused spaces
- chore: Routine tasks, maintenance, or tooling changes
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and its …
```
=> remove empty cookbook tabs

.ci/gen_pre_build_summ.sh, .ci/run-codeql-summ.sh, .github/workflows/gh-event-notification.yaml, .github/workflows/sast-codeql.yaml, .github/workflows/sca-scan.yaml, .github/workflows/smoke-test.yaml
Add SAST (codeql) workflow and Github event (PR and Issues) notification workflow.
Perform static code analysis for code security
- ci: Changes to the CI/CD configuration or scripts
Existing unit tests
<details>
```
Version 1.1
Developer's Certificate of Origin 1.1
By …
```
=> SAST workflow and GH even notification workflow

app/redteaming/(fullscreen)/components/__tests__/__snapshots__/chatbox.test.tsx.snap, app/redteaming/(fullscreen)/components/chatbox.tsx, app/redteaming/(fullscreen)/components/prompTalkBubble.tsx, app/redteaming/(fullscreen)/components/promptAndResponseTalkBubbles.tsx, app/redteaming/(fullscreen)/components/responseTalkBubble.tsx
- Change talk bubble title of prompts from Attack modules to  “Automated red teaming agent” 
- Change talk bubble titles of responses to "Response"
- Minor spacing between title and talk bubble
- Update test snapshot
Better distinction between automated and manual red team chats
- feat: A new feature 
<details> …
=> [MS-573][FE] update talk bubble labels and minor spacings

app/endpoints/(edit)/newEndpointForm.tsx
Quick text change - add asterisk to Token and Config textboxes labels in new/update endpoint form
Benchmark flow
1. Go into benchmark flow.
2. In select endpoint screen, click New Endpoint button
3. Verify asterisks displayed
4. Back on select endpoint screen, click on edit button on an endpoint
5. Verify asterisks displayed
View Endpoints
1. Click Model Endpoints from left nav
2. Click Create new Endpoint button
3. Verify asterisks on the form
4. Go back
5. Click Edit Endpoint button
6. Verify asterisks on the form
- [x ]  I have …
=> [MS-567][FE] add asterisks to required inputs

app/redteaming/(fullscreen)/components/chatbox-free-layout.tsx, app/redteaming/(fullscreen)/components/chatbox-slide-layout.tsx, app/redteaming/(fullscreen)/hooks/useChatboxesPositionsUtils.ts
Fixes issue where RT chat windows sometimes do not get displayed on resume
Bugfix
- [x ]  I have added or updated the necessary documentation (README, API docs, etc.).
- [x ]  I have followed the project's coding conventions and style guidelines.
- [x ]  I have rebased my branch onto the latest commit of the main branch.
- [x ]  I have read, understood and agree to the Developer Certificate …
=> [MS-544][FE] bugfix - red team chat windows no rendered first time resumed

app/components/selectListItem.tsx, app/redteaming/(fullscreen)/components/attackModuleSelector.tsx
Small fix - long description of Attack Module in RT flow, overflows. Updated to enabled scrolling when mouse pointer hovers over.
Bug fix
Go through Start new RT session flow. Verify long description in select Attack Module screen.
<details>
```
Version 1.1
license document, but changing it is not …
```
=> [MS-638][FE] Fix/attack mod long desc

app/benchmarking/components/__tests__/benchmarkRunForm.test.tsx, app/benchmarking/components/benchmarkNewSessionFlow.tsx, app/benchmarking/components/benchmarkRunForm.tsx
Code changes to fix total prompts calculation bug.
bugfix. inaccurate display of total prompts
1.  Go into Benchmark Run flow
2.  On the Run form, verify `metrics` is not displayed in the formula in tooltip
3.  Also check that the calculated total prompts is correct
- x]  I have read, understood and agree to the Developer Certificate of Origin below, which this project utilises.
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux …
```
=> [MS-685][FE] Fix/total prompts calc

app/api/v1/endpoints/[id]/route.ts, next.config.js
Fixes intermittent issue where updating endpoint via the edit endpoint form did not update the values in data
Bugfix
1. Go to edit endpoint screen
2. Update values like token, connector type, etc
3. Verify the values got updated
<details>
```
Version 1.1 …
```
=> [MS-666][FE] Fix/put request caching

README.md
Fix broken link in readme where it points to non existent link in the documentation
<details>
```
Version 1.1
Everyone is …
```
=> [MS-695] Update README.md

app/benchmarking/components/__tests__/benchmarkNewSessionFlow.test.tsx, app/benchmarking/components/benchmarkNewSessionFlow.tsx, app/benchmarking/components/benchmarkNewSessionFlowReducer.ts
- Fix a bug where next icon was displayed in benchmark run form
- Removed duplicate test in benchmark flow test spec
bug fix
- Go through benchmark run flow
- Verify next icon is not displayed in the last screen (Benchmark Run form)
<details>
```
Version 1.1
license document, but changing it is not …
```
=> [MS-696][FE] Fix next icon showing on run form

actions/createReadteamSession.ts, app/benchmarking/components/__tests__/benchmarkNewSessionFlow.test.tsx, app/benchmarking/components/endpointsSelector.tsx, app/components/button/index.tsx, app/global.d.ts, app/redteaming/(fullscreen)/components/attackModuleSelector.tsx, app/redteaming/(others)/sessions/new/__tests__/redTeamNewSessionFlow.test.tsx, app/redteaming/(others)/sessions/new/__tests__/redTeamRunForm.test.tsx, app/redteaming/(others)/sessions/new/redteamNewSessionFlow.tsx, app/redteaming/(others)/sessions/new/redteamNewSessionFlowReducer.ts, app/redteaming/(others)/sessions/new/redteamRunForm.tsx, app/redteaming/(others)/sessions/runButton.tsx, app/services/session-api-service.ts
Red teaming new session flow was using `useState variables and setters` for state and the Run form was using formik.
This code changes updates the state management to use the `useReducer` api. For the form, form handling is refactored to use server action and Zod schema.
Unit tests added for ths RT flow.
- Simplify multi step form state management
- Update to latest react features for Form handling, which simplifies the code.
- chore: Routine tasks, maintenance, or tooling changes
1. Regression on Create New Red Team session flow
- []  I have added any necessary dependencies or packages to the project's build configuration.
[If the changes involve visual modifications, include screenshots or GIFs that demonstrate the …
=> [MS 253][FE] Refactor RT flow state management and add test coverage

app/api/types.ts, app/benchmarking/components/benchmarkRunStatus.tsx, app/benchmarking/components/benchmarkRunsView.tsx, app/benchmarking/runs/page.tsx, app/global.d.ts, moonshot.config.ts
UI currently do not support displaying recipe only runs which were executed on CLI. If recipe run exists, the whole View Past Runs screen will throw a parsing error and error boundary will prevent rendering the screen. This code change filters the runs with errors instead of blocking the screen with thrown error.
Blocked UX
1. Create a recipe run in CLI
2. Then go to UI and go to Benchmarking -> View Past Runs
<details>
```
Version 1.1 …
```
=> [MS-604][FE] Filter out cli recipe runs

app/endpoints/(edit)/newEndpointForm.tsx
Revert model textfield `required` validation in add/edit endpoint form
required validation not requried
Verify connector endpoint form saving - model input can be empty
<details>
```
Version 1.1
Developer's Certificate of Origin 1.1
By making a …
```
=> [MS-735] [FE] Fix / remove model required validation

package-lock.json
package-lock file needs to be updated so that `npm ci` command works.
It was not updated in previous PR because I was using `pnpm` and not `npm` on local machine.
- chore: Routine tasks, maintenance, or tooling changes 
<details>
<summary>Developer Certificate of …
=> [MS-825] update package-lock json

app/benchmarking/report/components/rawScoresTable.tsx, app/benchmarking/report/types/benchmarkReportTypes.ts
To support feature where benchmark raw metrics returns successful and unsuccessful prompt data 
PDF rendering will be slow the huge raw json data is not handled
- chore: Routine tasks, maintenance, or tooling changes 
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux …
```
=> [MS-842][FE] - fix report raw metrics rendering

app/benchmarking/report/components/rawScoresTable.tsx, app/benchmarking/report/types/benchmarkReportTypes.ts
In Sprint 21, there are new features and bug fixes introduced.
1. [FE] - fix report raw metrics rendering #85
To introduce more features and fixes for Moonshot.
<details>
```
Version 1.1
Everyone …
```
=> [Sprint 21] Fix

app/benchmarking/report/components/reportViewer.tsx, app/global.d.ts, package-lock.json, package.json
Changed html3pdf into html2pdf to resolve vulnerabilities surrounding DOMPurify, a dependency under html3pdf. 
html3pdf is a forked repo from html2pdf. However, it has DOMpurify as an additional dependency which has a XSS vulnerability. 
html3pdf has also not had a release since 2 years ago while html2pdf is more updated. 
Decision was made to change the report viewing download function to rely on the html2pdf package. 
Routine tasks, maintenance, or tooling changes
Run a benchmark test and download a report after a report is generated
NA
NA
```
Version 1.1
Everyone is permitted to copy and distribute verbatim copies of …
```
=> Moon 457 Resolve Vulnerabilities

app/benchmarking/components/benchmarkNewSessionFlow.tsx, app/benchmarking/components/benchmarkRunStatus.tsx, app/benchmarking/components/cookbooksSelection.tsx, app/benchmarking/components/endpointsSelector.tsx, app/benchmarking/report/page.tsx, app/entryBanners.tsx, moonshot.config.ts
Add IMDA Starterkit as a new category
Updated landing page Content
Updated Create Endpoint button content
Removed Section in running tests
other: Other changes that don't fit into the above categories
- [x ]  I have followed the project's coding conventions and style guidelines.
- [x ]  I have rebased my branch onto the latest commit of the main branch.
- [x ]  I have squashed …
=> Ws-62 Starter Kit Experience in Moonshot V0

package.json
Update release version from 0.6.4 to 0.7.0.
- other: Other changes that don't fit into the above categories
Manual test in UAT and ran integration test.
<details>
```
Version 1.1 …
```
=> [WS-78][Release] Upgrade version from 0.6.4 to 0.7.0

.ci/run-codeql-summ.sh, app/api/v1/apiUtils.ts, app/api/v1/benchmarks/cancel/[runner_id]/route.ts, app/api/v1/benchmarks/results/[executor_id]/route.ts, app/api/v1/cookbooks/[cookbook_id]/route.ts, app/api/v1/endpoints/[id]/route.ts, app/api/v1/recipes/[recipe_id]/route.ts, app/api/v1/runners/[id]/route.ts, app/api/v1/sessions/[session_id]/attack-module/[attack_id]/route.ts, app/api/v1/sessions/[session_id]/close/route.ts, app/api/v1/sessions/[session_id]/context-strategy/[id]/[numOfPrevPrompts]/route.ts, app/api/v1/sessions/[session_id]/prompt-template/[template_id]/route.ts, app/api/v1/sessions/[session_id]/prompt/route.ts, app/api/v1/sessions/[session_id]/route.ts
This pull request fixes a SAST code vulnerability for SSRP due to unrestricted and unsanitized user input into a fetch api call to the server. 
The fix implements a regex validation check to constraint user input to [a-z,A-Z,0-9,-_] characters only. This is under the assumption that no ID uses special characters [! @ # $ % < > , . ; :  etc.]
To remove the SSPR vulnerability
fix: A bug fix
N.A
N.A 
<details>
```
Version 1.1
Developer's Certificate of …
```
=> Sec fix Merge to 0.6.x

app/benchmarking/components/cookbooksSelection.tsx, app/components/link-constants.tsx, app/entryBanners.tsx
Added a link to go to https://aiverify-foundation.github.io/moonshot/detailed_guide/starter_kit_cookbooks/   as per
https://imda-dsl.atlassian.net/browse/WS-138
Content Update
Get to the pages listed in the ticket, click the links to see if they redirect to the correct html
- [x ]  I have read, understood and agree to the Developer Certificate of Origin below, which this project utilises.
[Add …
=> ws-138 Add links to starter kit

app/benchmarking/components/configureRequirementsItemCard.tsx, app/benchmarking/components/cookbookSelectionItem.tsx
…t WS-112
changed formatting and wording of requires in cookbook selection and endpoint configuration
Wording was not clear enough
Content Update
- [x ]  I have followed the project's coding conventions and style guidelines.
- [x ]  I have squashed or reorganized my commits into logical units.
- [ x]  I have read, understood and agree to the Developer Certificate of Origin below, which this project utilises. …
=> WS-112 Changed wording and formatting of requires: 

actions/createCookbook.ts, app/api/v1/benchmarks/cancel/[runner_id]/route.ts, app/api/v1/benchmarks/results/[executor_id]/route.ts, app/api/v1/cookbooks/[cookbook_id]/route.ts, app/api/v1/endpoints/[id]/route.ts, app/api/v1/recipes/[recipe_id]/route.ts, app/api/v1/runners/[id]/route.ts, app/api/v1/sessions/[session_id]/attack-module/[attack_id]/route.ts, app/api/v1/sessions/[session_id]/close/route.ts, app/api/v1/sessions/[session_id]/context-strategy/[id]/[numOfPrevPrompts]/route.ts, app/api/v1/sessions/[session_id]/prompt-template/[template_id]/route.ts, app/api/v1/sessions/[session_id]/prompt/route.ts, app/api/v1/sessions/[session_id]/route.ts, app/benchmarking/components/__tests__/benchmarkRunForm.test.tsx, app/benchmarking/components/benchmarkRunForm.tsx, app/benchmarking/components/benchmarkRunStatus.tsx, app/endpoints/(edit)/_tests_/newEndpointForm.test.tsx, app/redteaming/(others)/bookmarks/bookmarksViewList.tsx, app/redteaming/(others)/sessions/new/redteamNewSessionFlow.tsx, app/redteaming/(others)/sessions/new/redteamNewSessionFlowReducer.ts, package-lock.json
Reverts aiverify-foundation/moonshot-ui#121
=> Revert "0.6.x code changes"

package-lock.json
npm audit update 
https://github.com/aiverify-foundation/moonshot-ui/security/dependabot/19
https://github.com/aiverify-foundation/moonshot-ui/security/dependabot/17
<details>
```
Version 1.1 …
```
=> [Security update] Update of packages with npm audit

package.json
[Provide a brief description of the changes or features introduced by this pull request.]
<details>
```
Version 1.1
Everyone …
```
=> [Release] updated versioning to 0.7.3
